spring:
  application:
    name: gateway
  redis:
    host: 192.168.100.133
    port: 6379
    password: 123456
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

server:
  port: 8080

haalan:
  jwt:
    location: classpath:haalan.jks
    password: haalan123
    alias: haalan
    tokenTTL: 2h
  redis:
    host: 192.168.100.133
    port: 6379
    password: 123456
  auth:
    excludePaths:
      - /search/**
      - /api/user/login
      - /api/user/register


