spring:
  application:
    name: gateway
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

server:
  port: 8080

haalan:
  jwt:
    location: classpath:haalan.jks
    password: haalan123
    alias: haalan
    tokenTTL: 2h
  redis:
    host: 192.168.100.133
    port: 6379
    password: 123456
  auth:
    excludePaths:
      - /search/**
      - /api/user/login
      - /api/user/register
      - /api/payment/callback/**


