server:
  port: 8081

haalan:
  jwt:
    location: classpath:haalan.jks
    password: haalan123
    alias: haalan
    tokenTTL: 2h
  swagger:
    title: haalan秒杀接口文档
    description: 哈兰接口文档
    email: 417376585@qq.com
    contact: lyc
    package: com.haalan.user.controller
  db:
    database: user-db
  redis:










