haalan:
  db:
    host: 192.168.100.133 # 修改为你自己的虚拟机IP地址
    pw: 123456 # 修改为docker中的MySQL密码
    user: root
  redis:
    password: 123456
    host: 192.168.100.133
  es:
    host: 192.168.100.133:9200
  stoken:
    timeout: 60000

# 支付宝配置
alipay:
  app-id: 9021000163664721
  private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDFUY2sjCW0G4DOTWiazjboRCnNPFNzv9tezZJbnDcd/E31WEwuYlNrg21lvBJEpGFWfT/0pZFGCS1Y0VDaT2s/EgajGohXoTEPgE6LhGbavR2FSnist+6S90FlBAAyjhNjg3k4xmszVheqm2h23EznTEIFXC13LcxMq56iL6Ir59DLsd04fPxjCLVNXnThG3gOE152KLpEtZ3GUCLF42C8zFoNtHy1QV5D09IdIyZggIzbOd8/DNCkgtHgo0Q1xiNHHnR7JcoVLznW6wXk2hHXZVpC+PbjVva1pOw5mPGhxg+EIaTCNXf8JTgZIDgnpgcO/NJc+8Ww6fM8nYf2hVp/AgMBAAECggEABAgNh/f5ETv6nrxwJbGO56H05K+V2OiTl9VFZz/C1IcCJMAgFlaF881kn85+5Q4iuvymIN59IFwxo/3q0/sJaul4Xz68iGXPtcxeTnVvEIsKnl2OJ6E+a5xHpsO1KVNDzCW0hVdwe0UICMFSGhOYMqWZN7jRaPzzjqF3BUNJ4fG6WBvDYHVtB+pfg64/3jnC4IXeiRadnT61anIy7s0xW8p52mR3CsJdbHEQfQD+eJf4x066Nhjm9hHQCOtRpYXeEHeZmRtL2soH5cmU/QxcrbUfhNN7v/0/yxJKN9+46gtGUi2OypiKYHTSO+OQE6yvc6angBMgs2ALvNqktxHt4QKBgQD0QQRlUlGborjAZLw/rbzVVTgRs/3ZkrlactcG29hyuTDpBAytm5+9p6lsWhNVE0hF/iBMOpbpaX83RWJzScEwq99t8xwAMVC0M+HjTfrx3/iVQIkArujC5ssxIVK4j0FX8X7YOZ9rjZoMeaXKOjiYwEIyk1lurBGaSS4IBGnELwKBgQDOzrhF9O240se/v5LO0xUCQvFGdRcNE8/H+wblzt68HgXPUXst4t+6dRHwXBxYW9tJ3ohdItZxFQLRuD78u+7ZTkMHKTq9clNlvkim9jUFL9z0DSS3BcfpLwB8i5JbJfvBz3Tref4PTNtWUCyfZk2rbFfAV2AKcqKaKjvFNdsqsQKBgBgXUZesxt/S7OYNCYQ+XqGsBhu45RDQp/eD3DGQ/YhTO7+/5oA5GUhbgRpux/lcLYS5y/W40amz/hg1f8BfRe7HBQKTN+/M7WjYtS72QgoZTStrchffKJYQrXnrD32ko41JBHnPNSomjUsttGx90Zc/X0gdwHRqBFJzZVblGImBAoGBAK3ioo4vorIEiG9xZL8CPGfqYXQcf4U/YzWCnAoeJqmFlNz8ZdXvLK5aQPsYd7zTf05dDctBv4zVXcl4YX2fhvSwGSusPveLaRPjKrM30NzLobySUIyTD8PBAWe28xgwl74d8PENYdD7jnDEeMCOBEBemGnhDZ+7Q3zcheULo3wBAoGBAIGWmPn9mC4oNTELRat+D7HvI4SFZvbwoiFmKwLVjxzXnCn9TiVzHgax060arEtq/UcO7f5ESVXVGT74PLyNmH30I6cCXSmSffurYM+m1BV5DHwLVAUt/Jm8szH5OrdBRd6cgY08sxKMRoAD6WCk0bCHTYhTzGl7Y/Onk7SIYXvu
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjBgHiN+LLVi+tE2tStTgDDoNVtaOf1mDSQZJZSNhEGpLfux65fLJikpoo8rIaBqNPv05uR40w/6AtLmW3k50g9czDhX8Wi9rMZhBTH2BP9NlHkkKeMC8F/yKWC6L9EljZHsMNSpw+23iuuRIIwX3med9jlzPW72kfvgDCKvbIeaY3oZ7H6qDWpSLKUFtnYQnh2BeMftYp0IzWcuIKm65ZbqCMEYQzJTEO9aGdeXu6djHFj3TVJXpHOXlmVjdgGv5st1v3ucyrWskqmXUScFr3zoug12kouOVXn7fdwA+ZnA0mlVoilJyHMckzxjB8k6/Gt+DlkO1TFIOxeCtoyW74wIDAQAB
  server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  notify-url: http://your-domain.com/api/order/alipay/notify
  return-url: http://your-domain.com/pay/success