spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:192.168.100.133}:3306/item-db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
  redis:
    host: ${REDIS_HOST:192.168.100.133}
    port: 6379
    password: ${REDIS_PASSWORD:123456}
  cloud:
    nacos:
      config:
        enabled: false

haalan:
  db:
    host: ${MYSQL_HOST:192.168.100.133}
    pw: ${MYSQL_PASSWORD:123456}
    user: ${MYSQL_USER:root}
    database: item-db
  redis:
    password: ${REDIS_PASSWORD:123456}
    host: ${REDIS_HOST:192.168.100.133}
  es:
    host: ${ES_HOST:192.168.100.133}:9200
  mq:
    host: ${MQ_HOST:192.168.100.133}
  seata:
    nacoshost: ${NACOS_HOST:192.168.100.133}:8848
seata:
  service:
    grouplist:
      default: ${SEATA_HOST:192.168.100.133}:8099