server:
  port: 8082

haalan:
  swagger:
    title: haalan秒杀管理商品接口文档
    description: 哈兰接口文档
    email: 417376585@qq.com
    contact: lyc
    package: com.haalan.item.controller
  db:
    database: item-db
  redis:








